### ISSUE TITLE
SeriLoggerFactory does not remain registered with LogManager

### ISSUE THREAD

**Issue by wterpstra** [jstemerdink/EPi.Libraries.Logging.Serilog#2]
When using EPiServer 10.10.0 (or maybe even earlier versions) the LoggerFactory will not remain set on the EPiServer.Logging.LogManager. When resolving the EPiServer.Logging.ILogger it will now resolve the EPiServerLazyLogger. However, when registering it using the appsettings or loggerFactoryType attribute on the episerver.framework section it does work.

```
<appSettings>
     <add key="episerver:LoggerFactoryType" value="EPi.Libraries.Logging.Serilog.SeriLoggerFactory, EPi.Libraries.Logging.Serilog" />
</appSettings>
```
or
```
<episerver.framework loggerFactoryType="EPi.Libraries.Logging.Serilog.SeriLoggerFactory, EPi.Libraries.Logging.Serilog">
```
[(Source)](https://world.episerver.com/documentation/developer-guides/CMS/logging/logging-into--net-diagnostics-trace/)

I propose a change to remove the SeriLoggerFactory registeration with the EPiServer.Logging.LogManager from the InitializableModule and update the documentation to register the SeriLoggerFactory using the configuration as stated above.

Will make PR when I have the time (probably this weekend or so).

**Comment by jstemerdink** [comment]
The ILogger has been loaded lazy in the LogManager since at least 9.12. So I don't think that's the core issue. 
By adding those settings you skip the scanning/discovery, so there maybe something in the initialization / order. You are using something different to initialize right?
I have tried it on the latest version, with the AppSettings provider I created and that seems to work ok.

**Comment by wterpstra** [comment]
Nope, I just let the the included SeriLoggerFactoryInitialization initialize it. I do have registered my own implementation of the ILoggerConfigurator but that shouldn't really matter I suppose. I will try to reproduce it on the Alloy and/or Quicksilver solutions and report back.
