### ISSUE TITLE
Serilog log doesn't work with the new version

### ISSUE THREAD

**Issue by ghost** [jstemerdink/EPi.Libraries.Logging.Serilog#3]
Hi, jstemerdink, 
I have the following cases:
1) Today I installed your packages in my EpiServer project and after update with the new versions of Serilog 2.6.0, I stopped receiving records in my log-file. Before that it worked fine.
2) When I removed EpiServer.Logging.Log4net I also stopped receiving records in my log-file.

I would like to use Serilog and JSON format with your libraries in my project. Could you tell me please what can I do to achieve my aim?

Thank you very much!

**Comment by jstemerdink** [comment]
What is the latest version of Serilog it worked with? Maybe they introduced a breaking change and did not up the Major version? Are you using the appsettings package I created?
If you remove EpiServer.Logging.Log4net You mean Serilog logging stopped?

**Comment by ghost** [comment]
Yeah..when I remove EpiServer.Logging.Log4net I don't receive any logs records. I use:
-  **Serilog 2.6.0**
I added also  **Serilog.Sinks.RollingFile 3.3.0** and put in the web.config :
`<add key="serilog:using:RollingFile" value="Serilog.Sinks.RollingFile" />`
But I don't have any serilog logs.

**Comment by jstemerdink** [comment]
Try installing Serilog.Settings.AppSettings if you usse the appesttings package. They moved it to there

**Comment by ghost** [comment]
I tried... no successful result :(
That are my packages:
` <package id="Serilog" version="2.6.0" targetFramework="net461" />
  <package id="Serilog.Settings.AppSettings" version="2.1.2" targetFramework="net461" />
  <package id="Serilog.Sinks.File" version="3.2.0" targetFramework="net461" />
  <package id="Serilog.Sinks.RollingFile" version="3.3.0" targetFramework="net461" />`

That are my settings in the **web.config**:
`  <add key="serilog:using:RollingFile" value="Serilog.Sinks.RollingFile" />
  <add key="serilog:minimum-level" value="Debug" />
  <add key="serilog:write-to:RollingFile.pathFormat" value="C:\Logs\EpiServerSeriLog-{Date}.txt" />
  <add key="serilog:write-to:RollingFile.retainedFileCountLimit" value="10" />`

**Comment by jstemerdink** [comment]
I have only tested Serilog with the absolute basic things. I have ugraded it to use the latest version of Episerver and Serilog, that's how I found out about the appsettings package. You could try to download the zip from the releases tab

**Comment by ghost** [comment]
With the zip files version 3.0.0 of  **EPi.Libraries.Logging.Serilog.AppSettings** and **EPi.Libraries.Logging.Serilog** works fine now...but when I uninstall EPiServer.Logging.Log4Net it stops again. As I can see your packages don't have a dependency on it. Could you check, please? 
Thanks !

**Comment by jstemerdink** [comment]
Are you using the LogManager from EPiServer.Logging.Compatibility, to do your logging calls? See https://world.episerver.com/documentation/Items/Developers-Guide/Episerver-CMS/9/Logging/logging-api/

There is no dependency on log4net in this library
